# Generated by Django 5.2.5 on 2025-10-13 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_medicalrecord_medicalimage_patient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('expiry_date', models.DateField(blank=True, help_text='Optional expiry date for medicines', null=True)),
                ('date_stock_in', models.DateField(auto_now_add=True)),
                ('stock', models.IntegerField(default=0, help_text='Minimum stock level threshold')),
                ('status', models.CharField(choices=[('In Stock', 'In Stock'), ('Low Stock', 'Low Stock'), ('Out of Stock', 'Out of Stock')], default='In Stock', max_length=20)),
                ('quantity', models.IntegerField(default=0, help_text='Current quantity in stock')),
                ('category', models.CharField(choices=[('Medicine', 'Medicine'), ('Equipment', 'Equipment'), ('Miscellaneous', 'Miscellaneous')], max_length=20)),
            ],
            options={
                'verbose_name': 'Inventory Item',
                'verbose_name_plural': 'Inventory Items',
                'ordering': ['-date_stock_in'],
            },
        ),
    ]
