# Generated by Django 5.2.5 on 2025-10-13 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_stocktransaction'),
    ]

    operations = [
    ]
