# Generated by Django 5.2.5 on 2025-10-13 03:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_add_stock_transaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(help_text='Full name of the patient', max_length=100)),
                ('patient_email', models.EmailField(help_text="Patient's email address", max_length=254)),
                ('patient_phone', models.CharField(help_text='Contact number', max_length=15)),
                ('date', models.DateField(help_text='Appointment date')),
                ('time', models.TimeField(help_text='Appointment time')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or special requests')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bookings', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(help_text='Service to be provided', on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='bookings.service')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'ordering': ['-date', '-time'],
            },
        ),
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_fee', models.DecimalField(decimal_places=2, help_text='Fee for the service provided', max_digits=10)),
                ('medicine_fee', models.DecimalField(decimal_places=2, default=0.0, help_text='Cost of medicines used', max_digits=10)),
                ('additional_fee', models.DecimalField(decimal_places=2, default=0.0, help_text='Any additional charges', max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, help_text='Discount amount', max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, editable=False, help_text='Total amount (auto-calculated)', max_digits=10)),
                ('is_paid', models.BooleanField(default=False, help_text='Automatically updated when payments cover total')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, editable=False, help_text='Total amount paid (auto-calculated)', max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, editable=False, help_text='Remaining balance (auto-calculated)', max_digits=10)),
                ('issued_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, help_text='Billing notes')),
                ('booking', models.OneToOneField(help_text='Associated booking', on_delete=django.db.models.deletion.CASCADE, related_name='billing', to='bookings.booking')),
            ],
            options={
                'verbose_name': 'Billing',
                'verbose_name_plural': 'Billings',
                'ordering': ['-issued_date'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, help_text='Amount paid in this transaction', max_digits=10)),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('GCash', 'GCash'), ('Bank Transfer', 'Bank Transfer'), ('Card', 'Credit/Debit Card'), ('Other', 'Other')], help_text='Method of payment', max_length=20)),
                ('reference_number', models.CharField(blank=True, help_text='Transaction reference number (optional)', max_length=100)),
                ('notes', models.TextField(blank=True, help_text='Payment notes or remarks')),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('billing', models.ForeignKey(help_text='Associated billing record', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='bookings.billing')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-payment_date'],
            },
        ),
    ]
