# Generated by Django 5.2.7 on 2025-10-13 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_booking_billing_payment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Unit price in PHP', max_digits=10),
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, help_text='Quantity prescribed')),
                ('dosage', models.CharField(help_text="e.g., '1 tablet twice daily'", max_length=100)),
                ('duration', models.CharField(blank=True, help_text="e.g., '7 days', '2 weeks'", max_length=100)),
                ('instructions', models.TextField(blank=True, help_text='Additional instructions for the patient')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price per unit at time of prescription', max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, editable=False, help_text='Total cost (auto-calculated)', max_digits=10)),
                ('prescribed_date', models.DateTimeField(auto_now_add=True)),
                ('medical_record', models.ForeignKey(help_text='Associated medical record', on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='bookings.medicalrecord')),
                ('medicine', models.ForeignKey(help_text='Medicine from inventory', limit_choices_to={'category': 'Medicine'}, on_delete=django.db.models.deletion.PROTECT, to='bookings.inventory')),
                ('prescribed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescribed_medications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prescription',
                'verbose_name_plural': 'Prescriptions',
                'ordering': ['-prescribed_date'],
            },
        ),
    ]
