# Generated by Django 5.2.5 on 2025-10-13 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_inventory_price_prescription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='POSSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(editable=False, help_text='Auto-generated receipt number', max_length=50, unique=True)),
                ('sale_date', models.DateTimeField(auto_now_add=True)),
                ('sale_type', models.CharField(choices=[('Walk-in', 'Walk-in Customer'), ('Patient', 'Registered Patient')], default='Walk-in', help_text='Type of customer', max_length=20)),
                ('customer_name', models.CharField(help_text='Customer name (required for walk-ins)', max_length=100)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, editable=False, help_text='Subtotal before discount', max_digits=10)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0.0, help_text='Discount percentage (0-100)', max_digits=5)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, editable=False, help_text='Discount amount (auto-calculated)', max_digits=10)),
                ('tax_percent', models.DecimalField(decimal_places=2, default=0.0, help_text='Tax percentage (0-100)', max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, editable=False, help_text='Tax amount (auto-calculated)', max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, editable=False, help_text='Final total amount', max_digits=10)),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('GCash', 'GCash'), ('Bank Transfer', 'Bank Transfer'), ('Card', 'Credit/Debit Card'), ('Other', 'Other')], default='Cash', max_length=20)),
                ('amount_received', models.DecimalField(decimal_places=2, default=0.0, help_text='Amount received from customer', max_digits=10)),
                ('change_amount', models.DecimalField(decimal_places=2, default=0.0, editable=False, help_text='Change given to customer', max_digits=10)),
                ('reference_number', models.CharField(blank=True, help_text='Payment reference number (for electronic payments)', max_length=100)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Refunded', 'Refunded')], default='Pending', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional notes')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_sales', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, help_text='Optional: Link to registered patient', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_sales', to='bookings.patient')),
            ],
            options={
                'verbose_name': 'POS Sale',
                'verbose_name_plural': 'POS Sales',
                'ordering': ['-sale_date'],
            },
        ),
        migrations.CreateModel(
            name='POSSaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, help_text='Quantity sold')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price per unit at time of sale', max_digits=10)),
                ('line_total', models.DecimalField(decimal_places=2, editable=False, help_text='Line total (quantity × unit price)', max_digits=10)),
                ('notes', models.CharField(blank=True, help_text='Item-specific notes', max_length=255)),
                ('inventory_item', models.ForeignKey(help_text='Item from inventory', on_delete=django.db.models.deletion.PROTECT, to='bookings.inventory')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bookings.possale')),
            ],
            options={
                'verbose_name': 'Sale Item',
                'verbose_name_plural': 'Sale Items',
                'ordering': ['id'],
            },
        ),
    ]
