# Generated by Django 5.2.5 on 2025-10-15 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_possale_possaleitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Service price in Philippine Pesos (₱)', max_digits=10),
        ),
    ]
