# Generated by Django 5.2.7 on 2025-10-15 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_service_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='consultation_status',
            field=models.CharField(choices=[('Not Yet', 'Not Yet'), ('Ongoing', 'Ongoing'), ('Done', 'Done')], default='Not Yet', help_text='Track consultation progress', max_length=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='consultation_status',
            field=models.CharField(choices=[('Not Yet', 'Not Yet'), ('Ongoing', 'Ongoing'), ('Done', 'Done')], default='Not Yet', help_text='Track consultation progress', max_length=10),
        ),
    ]
