# Generated by Django 5.2.7 on 2025-10-15 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0011_appointment_consultation_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='service_fee',
            field=models.DecimalField(decimal_places=2, default=500.0, help_text='Fee for the service provided', max_digits=10),
        ),
    ]
