# Generated by Django 5.2.7 on 2025-10-15 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0012_alter_billing_service_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled')], db_index=True, default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='billing',
            name='is_paid',
            field=models.BooleanField(db_index=True, default=False, help_text='Automatically updated when payments cover total'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='consultation_status',
            field=models.CharField(choices=[('Not Yet', 'Not Yet'), ('Ongoing', 'Ongoing'), ('Done', 'Done')], db_index=True, default='Not Yet', help_text='Track consultation progress', max_length=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(db_index=True, help_text='Appointment date'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], db_index=True, default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='category',
            field=models.CharField(choices=[('Medicine', 'Medicine'), ('Equipment', 'Equipment'), ('Miscellaneous', 'Miscellaneous')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='status',
            field=models.CharField(choices=[('In Stock', 'In Stock'), ('Low Stock', 'Low Stock'), ('Out of Stock', 'Out of Stock')], db_index=True, default='In Stock', max_length=20),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='visit_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='possale',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Refunded', 'Refunded')], db_index=True, default='Pending', max_length=20),
        ),
    ]
