# Generated by Django 5.2.5 on 2025-10-30 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0013_alter_appointment_created_at_alter_appointment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='custom_medicine_name',
            field=models.CharField(blank=True, help_text='Medicine name if not in inventory', max_length=255),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='medicine',
            field=models.ForeignKey(blank=True, help_text='Medicine from inventory', limit_choices_to={'category': 'Medicine'}, null=True, on_delete=django.db.models.deletion.PROTECT, to='bookings.inventory'),
        ),
    ]
