# Generated by Django 5.2.7 on 2025-11-03 06:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0014_prescription_custom_medicine_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['date', 'time'], name='bookings_bo_date_9ed98b_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', 'date'], name='bookings_bo_status_c5c45f_idx'),
        ),
    ]
