# Generated by Django 5.2.7 on 2025-11-03 06:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0016_billing_updated_by_alter_patient_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cancellation_reason',
            field=models.TextField(blank=True, help_text='Reason for cancellation'),
        ),
        migrations.AddField(
            model_name='booking',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, help_text='When this booking was cancelled', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, help_text='User who cancelled this booking', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='authorization_code',
            field=models.CharField(blank=True, help_text='Payment authorization code (for card/online payments)', max_length=100),
        ),
        migrations.AddField(
            model_name='payment',
            name='is_verified',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this payment has been verified'),
        ),
        migrations.AddField(
            model_name='payment',
            name='verified_at',
            field=models.DateTimeField(blank=True, help_text='When this payment was verified', null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='verified_by',
            field=models.ForeignKey(blank=True, help_text='User who verified this payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prescription',
            name='expiry_date',
            field=models.DateField(blank=True, db_index=True, help_text='Date when this prescription expires', null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='filled_by',
            field=models.ForeignKey(blank=True, help_text='User who dispensed this prescription', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filled_prescriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prescription',
            name='filled_date',
            field=models.DateTimeField(blank=True, help_text='When this prescription was dispensed', null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='is_filled',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this prescription has been dispensed'),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='approved_at',
            field=models.DateTimeField(blank=True, help_text='When this transaction was approved', null=True),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Supervisor who approved this transaction', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_stock_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='is_approved',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this transaction has been approved'),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason if transaction was rejected'),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='requires_approval',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this transaction needs supervisor approval'),
        ),
    ]
