# Generated by Django 5.2.7 on 2025-11-03 10:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0017_booking_cancellation_reason_booking_cancelled_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='billing',
            index=models.Index(fields=['is_paid', 'issued_date'], name='bookings_bi_is_paid_6bd373_idx'),
        ),
        migrations.AddIndex(
            model_name='billing',
            index=models.Index(fields=['booking', 'is_paid'], name='bookings_bi_booking_e8b714_idx'),
        ),
        migrations.AddIndex(
            model_name='billing',
            index=models.Index(fields=['issued_date', 'is_paid'], name='bookings_bi_issued__7ae69c_idx'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['category', 'status'], name='bookings_in_categor_535292_idx'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['status', 'quantity'], name='bookings_in_status_fe49db_idx'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['expiry_date'], name='bookings_in_expiry__c27464_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalrecord',
            index=models.Index(fields=['patient', 'visit_date'], name='bookings_me_patient_8f1c78_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalrecord',
            index=models.Index(fields=['visit_date', 'created_at'], name='bookings_me_visit_d_e1e4dc_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['user', 'created_at'], name='bookings_pa_user_id_234fd6_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['phone'], name='bookings_pa_phone_c41d43_idx'),
        ),
        migrations.AddIndex(
            model_name='possale',
            index=models.Index(fields=['sale_date', 'status'], name='bookings_po_sale_da_21dd4c_idx'),
        ),
        migrations.AddIndex(
            model_name='possale',
            index=models.Index(fields=['status', 'sale_date'], name='bookings_po_status_a6f37f_idx'),
        ),
        migrations.AddIndex(
            model_name='possale',
            index=models.Index(fields=['patient', 'sale_date'], name='bookings_po_patient_33eced_idx'),
        ),
        migrations.AddIndex(
            model_name='possale',
            index=models.Index(fields=['receipt_number'], name='bookings_po_receipt_f67c81_idx'),
        ),
    ]
