# Generated by Django 5.2.7 on 2025-11-03 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0018_add_performance_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('VIEW', 'View'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('PAYMENT', 'Payment'), ('ACCEPT', 'Accept'), ('DECLINE', 'Decline'), ('CANCEL', 'Cancel')], max_length=20)),
                ('model_name', models.CharField(help_text='Name of the model (e.g., Booking, Patient)', max_length=50)),
                ('object_id', models.IntegerField(blank=True, help_text='ID of the affected object', null=True)),
                ('description', models.TextField(help_text='Description of the action')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='bookings_ac_timesta_ac9748_idx'), models.Index(fields=['user', '-timestamp'], name='bookings_ac_user_id_1f0fc6_idx'), models.Index(fields=['model_name', '-timestamp'], name='bookings_ac_model_n_c01d5f_idx')],
            },
        ),
    ]
