# Generated by Django 5.2.7 on 2025-11-06 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0019_activitylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='consultation_status',
            field=models.CharField(choices=[('Not Yet', 'Not Yet'), ('Ongoing', 'Ongoing'), ('Done', 'Done'), ('No-Show', 'No-Show')], default='Not Yet', help_text='Track consultation progress', max_length=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='consultation_status',
            field=models.CharField(choices=[('Not Yet', 'Not Yet'), ('Ongoing', 'Ongoing'), ('Done', 'Done'), ('No-Show', 'No-Show')], db_index=True, default='Not Yet', help_text='Track consultation progress', max_length=10),
        ),
    ]
