# Generated by Django 5.2.7 on 2025-11-06 11:59

import bookings.models.patients
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0020_alter_appointment_consultation_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text="Patient's profile picture", null=True, upload_to=bookings.models.patients.profile_picture_upload_path),
        ),
    ]
