# Generated by Django 5.2.7 on 2025-11-09 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0021_patient_profile_picture'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text="Doctor's first name", max_length=100)),
                ('last_name', models.CharField(help_text="Doctor's last name", max_length=100)),
                ('specialization', models.CharField(help_text='Medical specialization (e.g., Dermatologist, Ophthalmologist)', max_length=200)),
                ('license_number', models.CharField(help_text='Professional license number', max_length=50, unique=True)),
                ('phone_number', models.CharField(help_text='Contact number', max_length=15)),
                ('email', models.EmailField(help_text='Email address', max_length=254)),
                ('qualifications', models.TextField(blank=True, help_text='Educational background and certifications')),
                ('years_of_experience', models.IntegerField(default=0, help_text='Years of professional experience')),
                ('is_available', models.BooleanField(default=True, help_text='Currently accepting appointments')),
                ('schedule_notes', models.TextField(blank=True, help_text='Working hours and availability notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_doctors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctors',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='doctor',
            field=models.ForeignKey(blank=True, help_text='Assigned doctor for this appointment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='bookings.doctor'),
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['last_name', 'first_name'], name='bookings_do_last_na_8fc46d_idx'),
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['is_available'], name='bookings_do_is_avai_62a0b2_idx'),
        ),
    ]
