# Generated by Django 5.2.7 on 2025-11-09 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0022_doctor_booking_doctor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, help_text='Date to block from bookings', unique=True)),
                ('reason', models.CharField(blank=True, help_text='Reason for blocking (e.g., Holiday, Clinic Closed)', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocked_dates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Blocked Date',
                'verbose_name_plural': 'Blocked Dates',
                'ordering': ['date'],
            },
        ),
    ]
