# Generated by Django 5.2.7 on 2025-11-09 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0023_blockeddate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='qualifications',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='years_of_experience',
        ),
    ]
