# Generated by Django 5.2.7 on 2025-11-09 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0025_add_service_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_time', models.TimeField(default='09:00', help_text='Clinic opening time (e.g., 09:00)')),
                ('closing_time', models.TimeField(default='17:00', help_text='Clinic closing time (e.g., 17:00)')),
                ('appointment_slot_duration', models.IntegerField(default=60, help_text='Duration of each appointment slot in minutes')),
                ('clinic_name', models.CharField(default='Romualdez Skin and Eye Clinic', help_text='Official clinic name', max_length=200)),
                ('clinic_address', models.TextField(blank=True, help_text='Full clinic address')),
                ('clinic_phone', models.CharField(blank=True, help_text='Main contact number', max_length=20)),
                ('clinic_email', models.EmailField(blank=True, help_text='Main email address', max_length=254)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Clinic Settings',
                'verbose_name_plural': 'Clinic Settings',
            },
        ),
    ]
