# Generated by Django 5.2.7 on 2025-11-09 17:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0026_add_clinic_settings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, help_text='Date for calendar entry', unique=True)),
                ('reason', models.CharField(blank=True, help_text='Reason or description (e.g., Holiday, Clinic Closed)', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Calendar Entry',
                'verbose_name_plural': 'Calendar',
                'db_table': 'bookings_calendar',
                'ordering': ['date'],
            },
        ),
    ]
