# Generated by Django 5.2.7 on 2025-11-09 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0027_calendar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendar',
            options={'ordering': ['date'], 'verbose_name': 'Calendar Event', 'verbose_name_plural': 'Calendar Events'},
        ),
        migrations.AddField(
            model_name='calendar',
            name='end_time',
            field=models.TimeField(blank=True, help_text='End time (for special operating hours)', null=True),
        ),
        migrations.AddField(
            model_name='calendar',
            name='event_type',
            field=models.CharField(choices=[('blocked', 'Blocked Date'), ('holiday', 'Holiday'), ('special_hours', 'Special Operating Hours')], db_index=True, default='blocked', help_text='Type of calendar event', max_length=20),
        ),
        migrations.AddField(
            model_name='calendar',
            name='start_time',
            field=models.TimeField(blank=True, help_text='Start time (for special operating hours)', null=True),
        ),
        migrations.AddField(
            model_name='calendar',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='date',
            field=models.DateField(db_index=True, help_text='Date of the calendar event'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='reason',
            field=models.CharField(blank=True, help_text='Reason for the calendar event (e.g., Holiday, Clinic Closed)', max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='calendar',
            unique_together={('date', 'event_type')},
        ),
        migrations.AddIndex(
            model_name='calendar',
            index=models.Index(fields=['date', 'event_type'], name='bookings_ca_date_d94486_idx'),
        ),
        migrations.AlterModelTable(
            name='calendar',
            table=None,
        ),
    ]
