# Generated by Django 5.2.7 on 2025-11-09 17:40

from django.db import migrations


def migrate_blocked_dates_to_calendar(apps, schema_editor):
    """
    Migrate all existing BlockedDate records to Calendar table.
    """
    BlockedDate = apps.get_model('bookings', 'BlockedDate')
    Calendar = apps.get_model('bookings', 'Calendar')
    
    # Copy all blocked dates to calendar
    blocked_dates = BlockedDate.objects.all()
    calendar_entries = []
    
    for blocked_date in blocked_dates:
        calendar_entries.append(
            Calendar(
                event_type='blocked',
                date=blocked_date.date,
                reason=blocked_date.reason,
                created_at=blocked_date.created_at,
                created_by=blocked_date.created_by
            )
        )
    
    # Bulk create calendar entries
    if calendar_entries:
        Calendar.objects.bulk_create(calendar_entries)


def reverse_migration(apps, schema_editor):
    """
    Remove calendar entries that were migrated from BlockedDate.
    """
    Calendar = apps.get_model('bookings', 'Calendar')
    Calendar.objects.filter(event_type='blocked').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0028_add_calendar_model'),
    ]

    operations = [
        migrations.RunPython(migrate_blocked_dates_to_calendar, reverse_migration),
    ]
